[degree]
name = "Software Engineering"
# parent = ""
source = "https://ugradcalendar.uwaterloo.ca/page/ENG-Software-Engineering"

[[requirements]]
name = "Three Advanced Technical Electives (ATE)"
cond = "<ATE_CS:1> and <ATE_ECE:1> and <ATE:3>"

[[requirements]]
name = "Two Science Electives (SCE)"
cond = "<SCE:2>"

[[requirements]]
name = "Three Linkage Electives (LE)"
cond = "<Societal_Issues:1> && <Humanities_and_Social_Sciences:1> && <Communications:1>"

[[requirements]]
name = "Communication course is taken in 2A"
cond = "![2A] || <Communications:1>"
apply = "every_term"

[[default_schedule.term]]
name = "1A"
courses = ["CS 137", "ECE 105", "MATH 115", "MATH 117", "MATH 135", "SE 101"]
