package com.watcourses.wat_courses.rules

val ALL_LABELS = listOf(
    "Accounting",
    "Accounting and Financial Management",
    "Actuarial Science",
    "Aging Studies",
    "Aging Studies Option",
    "Applied Health Sciences",
    "Architectural Engineering",
    "Architecture",
    "Arts",
    "Anthropology",
    "Aviation",
    "Aviation Specialization",
    "Anthropology",
    "Bachelor of Social Work",
    "Biochemistry",
    "Biology",
    "Biomechanics Option",
    "Biomedical Engineering",
    "Biomedical Sciences",
    "Biophysics specialization",
    "Biotechnology/Chartered Professional Accountancy",
    "Biotechnology/Economics",
    "Business",
    "Chemical Engineering",
    "Chemical Physics",
    "Chemistry",
    "Civil Engineering",
    "Co-op",
    "Computer Engineering",
    "Computer Engineering Option",
    "Computer Science",
    "Computing and Financial Management",
    "Data Science",
    "Department of Recreation and Leisure Studies",
    "Digital Arts Communication",
    "Digital Hardware Option",
    "Earth Science",
    "Earth and Environmental Sciences",
    "Economics",
    "EDGE",
    "Electrical Engineering",
    "Engineering",
    "English",
    "English Rhetoric and Professional Writing",
    "English Rhetoric, Media, and Professional Communication",
    "Environment and Business",
    "Environment and Resource",
    "Environment, Resources and Sustainability",
    "Environmental Engineering",
    "Environmental Science",
    "Environmental Studies",
    "Ergonomics",
    "Ergonomics and Injury Prevention",
    "Ergonomics Option",
    "Event Management Minor",
    "Exchange",
    "Faculty of Environment",
    "Faculty of Mathematics",
    "Faculty of Science",
    "Fine Arts",
    "Gender and Social Justice",
    "Geochemistry",
    "Geography",
    "Geography and Aviation",
    "Geography and Environmental Management",
    "Geological Engineering",
    "Geomatics",
    "Geoscience Specialization",
    "Gerontology",
    "Global Business",
    "Global Business and Digital Arts",
    "Health Informatics Option",
    "Health Promotion",
    "Health Studies",
    "History",
    "Honours",
    "Honours Speech Communication",
    "Human Resources Management",
    "Hydrogeology Specialization",
    "International Development",
    "Kinesiology",
    "Knowledge Integration",
    "Legal Studies",
    "Life Physics",
    "Make-Up Psychology",
    "Management Engineering",
    "Management Sciences Option",
    "Management Studies",
    "Materials and Nanosciences",
    "Mathematical Economics",
    "Mathematical Finance",
    "Mathematical Physics",
    "Mathematics",
    "Mathematics Health Informatics",
    "Mathematics Teaching",
    "Mathematics/Chartered Professional Accountancy",
    "Mathematics/Financial Analysis",
    "Mathematics/Financial Analysis and Risk Management",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Mechatronics Option",
    "Medicinal Chemistry",
    "Medical Physics Specialization",
    "Music",
    "Nanosciences",
    "Nanotechnology Engineering",
    "Optometry",
    "Peace and Conflict Studies",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Physics and Astronomy",
    "Planning",
    "Political Science",
    "Psychology",
    "Public Health",
    "Research Intensive Specialization",
    "Recreation and Business",
    "Recreation and Leisure Studies",
    "Recreation and Sport Business",
    "Rehabilitation Sciences",
    "Religious Studies",
    "School of Public Health and Health Systems",
    "Science",
    "Science and Aviation",
    "Sexuality, Marriage, and Family Studies",
    "Social Development Studies",
    "Social Policy",
    "Social Policy Specialization",
    "Society, Technology and Values",
    "Society, Technology and Values Option",
    "Sociology",
    "Software Engineering",
    "Software Engineering Option",
    "Statistics for Health",
    "Systems Design Engineering",
    "Theatre and Performance",
    "Therapeutic Recreation",
    "Tourism Option",
    "Visual Culture Honours",
    "Water Science Specialization"
)