package com.watcourses.wat_courses.rules

val ALL_LABELS = listOf(
    "Accounting and Financial Management",
    "Actuarial Science",
    "Aging Studies",
    "Applied Health Sciences",
    "Architectural",
    "Architectural Engineering",
    "Architecture",
    "Arts",
    "Anthropology",
    "Aviation",
    "Anthropology",
    "Bachelor of Social Work",
    "Biochemistry",
    "Biomedical Engineering",
    "Biomedical Sciences",
    "Biotechnology/Chartered Professional Accountancy",
    "Biotechnology/Economics",
    "Business",
    "Chemical Engineering",
    "Chemical Physics",
    "Chemistry",
    "Civil Engineering",
    "Civil",
    "Co-op",
    "Coop",
    "Computer Engineering",
    "Computer and Electrical Engineering",
    "Computer Science",
    "Computing and Financial Management",
    "Digital Arts Communication",
    "Earth Science",
    "Economics",
    "Edge",
    "Ergonomics",
    "Electrical Engineering",
    "Electrical and Computer Engineering",
    "Engineering",
    "English",
    "Environment and Business",
    "Environment, Resources and Sustainability",
    "Environmental",
    "Environmental Engineering",
    "Environmental Science",
    "Environmental Studies",
    "Ergonomics and Injury Prevention",
    "Exchange",
    "Faculty of Environment",
    "Faculty of Mathematics",
    "Faculty of Science",
    "Fine Arts",
    "Gender and Social Justice",
    "Geochemistry",
    "Geography",
    "Geography and Aviation",
    "Geography and Environmental Management",
    "Geological",
    "Geological Engineering",
    "Geomatics",
    "Gerontology",
    "Global Business",
    "Global Business and Digital Arts",
    "Health Studies",
    "Honours",
    "Honours Speech Communication",
    "Human Resources Management",
    "International Development",
    "Kinesiology",
    "Knowledge Integration",
    "Legal Studies",
    "Life Physics",
    "Make-Up Psychology",
    "Management Engineering",
    "Management Studies",
    "Materials and Nanosciences",
    "Mathematical Economics",
    "Mathematical Finance",
    "Mathematical Physics",
    "Mathematics",
    "Mathematics Health Informatics",
    "Mathematics Teaching",
    "Mathematics/Chartered Professional Accountancy",
    "Mathematics/Financial Analysis",
    "Mathematics/Financial Analysis and Risk Management",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Medicinal Chemistry",
    "Music",
    "Nanosciences",
    "Nanotechnology Engineering",
    "Optometry",
    "Peace and Conflict Studies",
    "Pharmacy",
    "Philosophy",
    "Physics",
    "Physics and Astronomy",
    "Planning",
    "Political Science",
    "Psychology",
    "Recreation and Leisure Studies",
    "Recreation and Sport Business",
    "Rehabilitation Sciences",
    "School of Public Health and Health Systems",
    "Science",
    "Science and Aviation",
    "Sexuality, Marriage, and Family Studies",
    "Social Development Studies",
    "Social Policy",
    "Society, Technology and Values",
    "Sociology",
    "Software Engineering",
    "Systems Design Engineering",
    "Systems Design",
    "Theatre and Performance",
    "Therapeutic Recreation",
    "Visual Culture Honours",
    "Water Science Specialization"
)