// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class BatchGetCourseRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val courseCodes: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<BatchGetCourseRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BatchGetCourseRequest) return false
    return unknownFields == other.unknownFields
        && courseCodes == other.courseCodes
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + courseCodes.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (courseCodes.isNotEmpty()) result += """courseCodes=${sanitize(courseCodes)}"""
    return result.joinToString(prefix = "BatchGetCourseRequest{", separator = ", ", postfix = "}")
  }

  fun copy(courseCodes: List<String> = this.courseCodes, unknownFields: ByteString =
      this.unknownFields): BatchGetCourseRequest = BatchGetCourseRequest(courseCodes, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<BatchGetCourseRequest> = object : ProtoAdapter<BatchGetCourseRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      BatchGetCourseRequest::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.BatchGetCourseRequest"
    ) {
      override fun encodedSize(value: BatchGetCourseRequest): Int = 
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.courseCodes) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: BatchGetCourseRequest) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.courseCodes)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): BatchGetCourseRequest {
        val courseCodes = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> courseCodes.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return BatchGetCourseRequest(
          courseCodes = courseCodes,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: BatchGetCourseRequest): BatchGetCourseRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
