// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: uwapi.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class Class(
  /**
   * Date object for course schedule
   */
  @field:WireField(
    tag = 1,
    adapter = "com.watcourses.wat_courses.proto.ClassDate#ADAPTER"
  )
  val date: ClassDate? = null,
  /**
   * Class location details
   */
  @field:WireField(
    tag = 2,
    adapter = "com.watcourses.wat_courses.proto.ClassLocation#ADAPTER"
  )
  val location: ClassLocation? = null,
  /**
   * Names of instructors teaching the course
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val instructors: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Class, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Class) return false
    return unknownFields == other.unknownFields
        && date == other.date
        && location == other.location
        && instructors == other.instructors
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + date.hashCode()
      result = result * 37 + location.hashCode()
      result = result * 37 + instructors.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (date != null) result += """date=$date"""
    if (location != null) result += """location=$location"""
    if (instructors.isNotEmpty()) result += """instructors=${sanitize(instructors)}"""
    return result.joinToString(prefix = "Class{", separator = ", ", postfix = "}")
  }

  fun copy(
    date: ClassDate? = this.date,
    location: ClassLocation? = this.location,
    instructors: List<String> = this.instructors,
    unknownFields: ByteString = this.unknownFields
  ): Class = Class(date, location, instructors, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Class> = object : ProtoAdapter<Class>(
      FieldEncoding.LENGTH_DELIMITED, 
      Class::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.Class"
    ) {
      override fun encodedSize(value: Class): Int = 
        ClassDate.ADAPTER.encodedSizeWithTag(1, value.date) +
        ClassLocation.ADAPTER.encodedSizeWithTag(2, value.location) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.instructors) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: Class) {
        ClassDate.ADAPTER.encodeWithTag(writer, 1, value.date)
        ClassLocation.ADAPTER.encodeWithTag(writer, 2, value.location)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.instructors)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Class {
        var date: ClassDate? = null
        var location: ClassLocation? = null
        val instructors = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> date = ClassDate.ADAPTER.decode(reader)
            2 -> location = ClassLocation.ADAPTER.decode(reader)
            3 -> instructors.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return Class(
          date = date,
          location = location,
          instructors = instructors,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Class): Class = value.copy(
        date = value.date?.let(ClassDate.ADAPTER::redact),
        location = value.location?.let(ClassLocation.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
