// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.redactElements
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CourseSection(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val section: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val location: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val enrolCap: Int? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val enrolTotal: Int? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val time: List<String> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val room: String? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val instructor: String? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val sectionId: Int? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.watcourses.wat_courses.proto.ReservedEnrolInfo#ADAPTER",
    label = WireField.Label.REPEATED
  )
  val reservedEnrolInfo: List<ReservedEnrolInfo> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CourseSection, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CourseSection) return false
    return unknownFields == other.unknownFields
        && section == other.section
        && location == other.location
        && enrolCap == other.enrolCap
        && enrolTotal == other.enrolTotal
        && time == other.time
        && room == other.room
        && instructor == other.instructor
        && sectionId == other.sectionId
        && reservedEnrolInfo == other.reservedEnrolInfo
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + section.hashCode()
      result = result * 37 + location.hashCode()
      result = result * 37 + enrolCap.hashCode()
      result = result * 37 + enrolTotal.hashCode()
      result = result * 37 + time.hashCode()
      result = result * 37 + room.hashCode()
      result = result * 37 + instructor.hashCode()
      result = result * 37 + sectionId.hashCode()
      result = result * 37 + reservedEnrolInfo.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (section != null) result += """section=${sanitize(section)}"""
    if (location != null) result += """location=${sanitize(location)}"""
    if (enrolCap != null) result += """enrolCap=$enrolCap"""
    if (enrolTotal != null) result += """enrolTotal=$enrolTotal"""
    if (time.isNotEmpty()) result += """time=${sanitize(time)}"""
    if (room != null) result += """room=${sanitize(room)}"""
    if (instructor != null) result += """instructor=${sanitize(instructor)}"""
    if (sectionId != null) result += """sectionId=$sectionId"""
    if (reservedEnrolInfo.isNotEmpty()) result += """reservedEnrolInfo=$reservedEnrolInfo"""
    return result.joinToString(prefix = "CourseSection{", separator = ", ", postfix = "}")
  }

  fun copy(
    section: String? = this.section,
    location: String? = this.location,
    enrolCap: Int? = this.enrolCap,
    enrolTotal: Int? = this.enrolTotal,
    time: List<String> = this.time,
    room: String? = this.room,
    instructor: String? = this.instructor,
    sectionId: Int? = this.sectionId,
    reservedEnrolInfo: List<ReservedEnrolInfo> = this.reservedEnrolInfo,
    unknownFields: ByteString = this.unknownFields
  ): CourseSection = CourseSection(section, location, enrolCap, enrolTotal, time, room, instructor,
      sectionId, reservedEnrolInfo, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CourseSection> = object : ProtoAdapter<CourseSection>(
      FieldEncoding.LENGTH_DELIMITED, 
      CourseSection::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.CourseSection"
    ) {
      override fun encodedSize(value: CourseSection): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.section) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.location) +
        ProtoAdapter.INT32.encodedSizeWithTag(3, value.enrolCap) +
        ProtoAdapter.INT32.encodedSizeWithTag(4, value.enrolTotal) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(5, value.time) +
        ProtoAdapter.STRING.encodedSizeWithTag(6, value.room) +
        ProtoAdapter.STRING.encodedSizeWithTag(7, value.instructor) +
        ProtoAdapter.INT32.encodedSizeWithTag(8, value.sectionId) +
        ReservedEnrolInfo.ADAPTER.asRepeated().encodedSizeWithTag(9, value.reservedEnrolInfo) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CourseSection) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.section)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.location)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.enrolCap)
        ProtoAdapter.INT32.encodeWithTag(writer, 4, value.enrolTotal)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.time)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.room)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.instructor)
        ProtoAdapter.INT32.encodeWithTag(writer, 8, value.sectionId)
        ReservedEnrolInfo.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.reservedEnrolInfo)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CourseSection {
        var section: String? = null
        var location: String? = null
        var enrolCap: Int? = null
        var enrolTotal: Int? = null
        val time = mutableListOf<String>()
        var room: String? = null
        var instructor: String? = null
        var sectionId: Int? = null
        val reservedEnrolInfo = mutableListOf<ReservedEnrolInfo>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> section = ProtoAdapter.STRING.decode(reader)
            2 -> location = ProtoAdapter.STRING.decode(reader)
            3 -> enrolCap = ProtoAdapter.INT32.decode(reader)
            4 -> enrolTotal = ProtoAdapter.INT32.decode(reader)
            5 -> time.add(ProtoAdapter.STRING.decode(reader))
            6 -> room = ProtoAdapter.STRING.decode(reader)
            7 -> instructor = ProtoAdapter.STRING.decode(reader)
            8 -> sectionId = ProtoAdapter.INT32.decode(reader)
            9 -> reservedEnrolInfo.add(ReservedEnrolInfo.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return CourseSection(
          section = section,
          location = location,
          enrolCap = enrolCap,
          enrolTotal = enrolTotal,
          time = time,
          room = room,
          instructor = instructor,
          sectionId = sectionId,
          reservedEnrolInfo = reservedEnrolInfo,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CourseSection): CourseSection = value.copy(
        reservedEnrolInfo = value.reservedEnrolInfo.redactElements(ReservedEnrolInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
