// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CourseInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val name: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val code: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val description: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val faculty: String? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.watcourses.wat_courses.proto.Term#ADAPTER",
    label = WireField.Label.REPEATED
  )
  val offeringTerms: List<Term> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val id: String? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.watcourses.wat_courses.proto.RuleInfo#ADAPTER"
  )
  val preRequisite: RuleInfo? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.watcourses.wat_courses.proto.RuleInfo#ADAPTER"
  )
  val coRequisite: RuleInfo? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.watcourses.wat_courses.proto.RuleInfo#ADAPTER"
  )
  val antiRequisite: RuleInfo? = null,
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val liked: Double? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val useful: Double? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val easy: Double? = null,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val commentsCount: Int? = null,
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val ratingsCount: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CourseInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CourseInfo) return false
    return unknownFields == other.unknownFields
        && name == other.name
        && code == other.code
        && description == other.description
        && faculty == other.faculty
        && offeringTerms == other.offeringTerms
        && id == other.id
        && preRequisite == other.preRequisite
        && coRequisite == other.coRequisite
        && antiRequisite == other.antiRequisite
        && liked == other.liked
        && useful == other.useful
        && easy == other.easy
        && commentsCount == other.commentsCount
        && ratingsCount == other.ratingsCount
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + code.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + faculty.hashCode()
      result = result * 37 + offeringTerms.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + preRequisite.hashCode()
      result = result * 37 + coRequisite.hashCode()
      result = result * 37 + antiRequisite.hashCode()
      result = result * 37 + liked.hashCode()
      result = result * 37 + useful.hashCode()
      result = result * 37 + easy.hashCode()
      result = result * 37 + commentsCount.hashCode()
      result = result * 37 + ratingsCount.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (name != null) result += """name=${sanitize(name)}"""
    if (code != null) result += """code=${sanitize(code)}"""
    if (description != null) result += """description=${sanitize(description)}"""
    if (faculty != null) result += """faculty=${sanitize(faculty)}"""
    if (offeringTerms.isNotEmpty()) result += """offeringTerms=$offeringTerms"""
    if (id != null) result += """id=${sanitize(id)}"""
    if (preRequisite != null) result += """preRequisite=$preRequisite"""
    if (coRequisite != null) result += """coRequisite=$coRequisite"""
    if (antiRequisite != null) result += """antiRequisite=$antiRequisite"""
    if (liked != null) result += """liked=$liked"""
    if (useful != null) result += """useful=$useful"""
    if (easy != null) result += """easy=$easy"""
    if (commentsCount != null) result += """commentsCount=$commentsCount"""
    if (ratingsCount != null) result += """ratingsCount=$ratingsCount"""
    return result.joinToString(prefix = "CourseInfo{", separator = ", ", postfix = "}")
  }

  fun copy(
    name: String? = this.name,
    code: String? = this.code,
    description: String? = this.description,
    faculty: String? = this.faculty,
    offeringTerms: List<Term> = this.offeringTerms,
    id: String? = this.id,
    preRequisite: RuleInfo? = this.preRequisite,
    coRequisite: RuleInfo? = this.coRequisite,
    antiRequisite: RuleInfo? = this.antiRequisite,
    liked: Double? = this.liked,
    useful: Double? = this.useful,
    easy: Double? = this.easy,
    commentsCount: Int? = this.commentsCount,
    ratingsCount: Int? = this.ratingsCount,
    unknownFields: ByteString = this.unknownFields
  ): CourseInfo = CourseInfo(name, code, description, faculty, offeringTerms, id, preRequisite,
      coRequisite, antiRequisite, liked, useful, easy, commentsCount, ratingsCount, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CourseInfo> = object : ProtoAdapter<CourseInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      CourseInfo::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.CourseInfo"
    ) {
      override fun encodedSize(value: CourseInfo): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.code) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.description) +
        ProtoAdapter.STRING.encodedSizeWithTag(4, value.faculty) +
        Term.ADAPTER.asRepeated().encodedSizeWithTag(5, value.offeringTerms) +
        ProtoAdapter.STRING.encodedSizeWithTag(6, value.id) +
        RuleInfo.ADAPTER.encodedSizeWithTag(7, value.preRequisite) +
        RuleInfo.ADAPTER.encodedSizeWithTag(8, value.coRequisite) +
        RuleInfo.ADAPTER.encodedSizeWithTag(9, value.antiRequisite) +
        ProtoAdapter.DOUBLE.encodedSizeWithTag(10, value.liked) +
        ProtoAdapter.DOUBLE.encodedSizeWithTag(11, value.useful) +
        ProtoAdapter.DOUBLE.encodedSizeWithTag(12, value.easy) +
        ProtoAdapter.INT32.encodedSizeWithTag(13, value.commentsCount) +
        ProtoAdapter.INT32.encodedSizeWithTag(14, value.ratingsCount) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CourseInfo) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.code)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.description)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.faculty)
        Term.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.offeringTerms)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.id)
        RuleInfo.ADAPTER.encodeWithTag(writer, 7, value.preRequisite)
        RuleInfo.ADAPTER.encodeWithTag(writer, 8, value.coRequisite)
        RuleInfo.ADAPTER.encodeWithTag(writer, 9, value.antiRequisite)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 10, value.liked)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 11, value.useful)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 12, value.easy)
        ProtoAdapter.INT32.encodeWithTag(writer, 13, value.commentsCount)
        ProtoAdapter.INT32.encodeWithTag(writer, 14, value.ratingsCount)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CourseInfo {
        var name: String? = null
        var code: String? = null
        var description: String? = null
        var faculty: String? = null
        val offeringTerms = mutableListOf<Term>()
        var id: String? = null
        var preRequisite: RuleInfo? = null
        var coRequisite: RuleInfo? = null
        var antiRequisite: RuleInfo? = null
        var liked: Double? = null
        var useful: Double? = null
        var easy: Double? = null
        var commentsCount: Int? = null
        var ratingsCount: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> code = ProtoAdapter.STRING.decode(reader)
            3 -> description = ProtoAdapter.STRING.decode(reader)
            4 -> faculty = ProtoAdapter.STRING.decode(reader)
            5 -> try {
              offeringTerms.add(Term.ADAPTER.decode(reader))
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            6 -> id = ProtoAdapter.STRING.decode(reader)
            7 -> preRequisite = RuleInfo.ADAPTER.decode(reader)
            8 -> coRequisite = RuleInfo.ADAPTER.decode(reader)
            9 -> antiRequisite = RuleInfo.ADAPTER.decode(reader)
            10 -> liked = ProtoAdapter.DOUBLE.decode(reader)
            11 -> useful = ProtoAdapter.DOUBLE.decode(reader)
            12 -> easy = ProtoAdapter.DOUBLE.decode(reader)
            13 -> commentsCount = ProtoAdapter.INT32.decode(reader)
            14 -> ratingsCount = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CourseInfo(
          name = name,
          code = code,
          description = description,
          faculty = faculty,
          offeringTerms = offeringTerms,
          id = id,
          preRequisite = preRequisite,
          coRequisite = coRequisite,
          antiRequisite = antiRequisite,
          liked = liked,
          useful = useful,
          easy = easy,
          commentsCount = commentsCount,
          ratingsCount = ratingsCount,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CourseInfo): CourseInfo = value.copy(
        preRequisite = value.preRequisite?.let(RuleInfo.ADAPTER::redact),
        coRequisite = value.coRequisite?.let(RuleInfo.ADAPTER::redact),
        antiRequisite = value.antiRequisite?.let(RuleInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
