// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: grpc.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.Service
import com.squareup.wire.WireRpc

interface CourseServiceServer : Service {
  @WireRpc(
    path = "/com.watcourses.wat_courses.proto.CourseService/getCourseInfo",
    requestAdapter = "com.watcourses.wat_courses.proto.CourseInfoRequest#ADAPTER",
    responseAdapter = "com.watcourses.wat_courses.proto.CourseInfo#ADAPTER"
  )
  suspend fun getCourseInfo(request: CourseInfoRequest): CourseInfo
}
