// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CreateDefaultStudentProfileRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val degrees: List<String> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val startingYear: Int? = null,
  /**
   * not used for now.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.watcourses.wat_courses.proto.CoopStream#ADAPTER"
  )
  val coopStream: CoopStream? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.watcourses.wat_courses.proto.Schedule#ADAPTER"
  )
  val schedule: Schedule? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CreateDefaultStudentProfileRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CreateDefaultStudentProfileRequest) return false
    return unknownFields == other.unknownFields
        && degrees == other.degrees
        && startingYear == other.startingYear
        && coopStream == other.coopStream
        && schedule == other.schedule
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + degrees.hashCode()
      result = result * 37 + startingYear.hashCode()
      result = result * 37 + coopStream.hashCode()
      result = result * 37 + schedule.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (degrees.isNotEmpty()) result += """degrees=${sanitize(degrees)}"""
    if (startingYear != null) result += """startingYear=$startingYear"""
    if (coopStream != null) result += """coopStream=$coopStream"""
    if (schedule != null) result += """schedule=$schedule"""
    return result.joinToString(prefix = "CreateDefaultStudentProfileRequest{", separator = ", ",
        postfix = "}")
  }

  fun copy(
    degrees: List<String> = this.degrees,
    startingYear: Int? = this.startingYear,
    coopStream: CoopStream? = this.coopStream,
    schedule: Schedule? = this.schedule,
    unknownFields: ByteString = this.unknownFields
  ): CreateDefaultStudentProfileRequest = CreateDefaultStudentProfileRequest(degrees, startingYear,
      coopStream, schedule, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CreateDefaultStudentProfileRequest> = object :
        ProtoAdapter<CreateDefaultStudentProfileRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      CreateDefaultStudentProfileRequest::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.CreateDefaultStudentProfileRequest"
    ) {
      override fun encodedSize(value: CreateDefaultStudentProfileRequest): Int = 
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.degrees) +
        ProtoAdapter.INT32.encodedSizeWithTag(2, value.startingYear) +
        CoopStream.ADAPTER.encodedSizeWithTag(3, value.coopStream) +
        Schedule.ADAPTER.encodedSizeWithTag(4, value.schedule) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CreateDefaultStudentProfileRequest) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.degrees)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.startingYear)
        CoopStream.ADAPTER.encodeWithTag(writer, 3, value.coopStream)
        Schedule.ADAPTER.encodeWithTag(writer, 4, value.schedule)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CreateDefaultStudentProfileRequest {
        val degrees = mutableListOf<String>()
        var startingYear: Int? = null
        var coopStream: CoopStream? = null
        var schedule: Schedule? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> degrees.add(ProtoAdapter.STRING.decode(reader))
            2 -> startingYear = ProtoAdapter.INT32.decode(reader)
            3 -> try {
              coopStream = CoopStream.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> schedule = Schedule.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CreateDefaultStudentProfileRequest(
          degrees = degrees,
          startingYear = startingYear,
          coopStream = coopStream,
          schedule = schedule,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CreateDefaultStudentProfileRequest):
          CreateDefaultStudentProfileRequest = value.copy(
        schedule = value.schedule?.let(Schedule.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
