// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.Map
import kotlin.jvm.JvmField
import okio.ByteString

class FindSlotResponse(
  /**
   * The term name and check results of the corresponding slot
   */
  @field:WireField(
    tag = 1,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.watcourses.wat_courses.proto.CheckResults#ADAPTER"
  )
  val slot: Map<String, CheckResults> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<FindSlotResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FindSlotResponse) return false
    return unknownFields == other.unknownFields
        && slot == other.slot
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + slot.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (slot.isNotEmpty()) result += """slot=$slot"""
    return result.joinToString(prefix = "FindSlotResponse{", separator = ", ", postfix = "}")
  }

  fun copy(slot: Map<String, CheckResults> = this.slot, unknownFields: ByteString =
      this.unknownFields): FindSlotResponse = FindSlotResponse(slot, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<FindSlotResponse> = object : ProtoAdapter<FindSlotResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      FindSlotResponse::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.FindSlotResponse"
    ) {
      private val slotAdapter: ProtoAdapter<Map<String, CheckResults>> =
          ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, CheckResults.ADAPTER)

      override fun encodedSize(value: FindSlotResponse): Int = 
        slotAdapter.encodedSizeWithTag(1, value.slot) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: FindSlotResponse) {
        slotAdapter.encodeWithTag(writer, 1, value.slot)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): FindSlotResponse {
        val slot = mutableMapOf<String, CheckResults>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> slot.putAll(slotAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return FindSlotResponse(
          slot = slot,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: FindSlotResponse): FindSlotResponse = value.copy(
        slot = value.slot.redactElements(CheckResults.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
