// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.Service
import com.squareup.wire.WireRpc

interface GreeterServer : Service {
  @WireRpc(
    path = "/com.watcourses.wat_courses.proto.Greeter/SayHello",
    requestAdapter = "com.watcourses.wat_courses.proto.HelloRequest#ADAPTER",
    responseAdapter = "com.watcourses.wat_courses.proto.HelloReply#ADAPTER"
  )
  suspend fun SayHello(request: HelloRequest): HelloReply
}
