// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class PaginationInfoRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val zeroBasedPage: Int? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val limit: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PaginationInfoRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PaginationInfoRequest) return false
    return unknownFields == other.unknownFields
        && zeroBasedPage == other.zeroBasedPage
        && limit == other.limit
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + zeroBasedPage.hashCode()
      result = result * 37 + limit.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (zeroBasedPage != null) result += """zeroBasedPage=$zeroBasedPage"""
    if (limit != null) result += """limit=$limit"""
    return result.joinToString(prefix = "PaginationInfoRequest{", separator = ", ", postfix = "}")
  }

  fun copy(
    zeroBasedPage: Int? = this.zeroBasedPage,
    limit: Int? = this.limit,
    unknownFields: ByteString = this.unknownFields
  ): PaginationInfoRequest = PaginationInfoRequest(zeroBasedPage, limit, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PaginationInfoRequest> = object : ProtoAdapter<PaginationInfoRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      PaginationInfoRequest::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.PaginationInfoRequest"
    ) {
      override fun encodedSize(value: PaginationInfoRequest): Int = 
        ProtoAdapter.INT32.encodedSizeWithTag(1, value.zeroBasedPage) +
        ProtoAdapter.INT32.encodedSizeWithTag(2, value.limit) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: PaginationInfoRequest) {
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.zeroBasedPage)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.limit)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PaginationInfoRequest {
        var zeroBasedPage: Int? = null
        var limit: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> zeroBasedPage = ProtoAdapter.INT32.decode(reader)
            2 -> limit = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PaginationInfoRequest(
          zeroBasedPage = zeroBasedPage,
          limit = limit,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PaginationInfoRequest): PaginationInfoRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
