// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: uwapi.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class Reserve(
  /**
   * Name of the reserved group
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val reserveGroup: String? = null,
  /**
   * Total enrollment capacity of the group
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val enrollmentCapacity: Int? = null,
  /**
   * Total reserve enrollment
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val enrollmentTotal: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<Reserve, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Reserve) return false
    return unknownFields == other.unknownFields
        && reserveGroup == other.reserveGroup
        && enrollmentCapacity == other.enrollmentCapacity
        && enrollmentTotal == other.enrollmentTotal
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + reserveGroup.hashCode()
      result = result * 37 + enrollmentCapacity.hashCode()
      result = result * 37 + enrollmentTotal.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (reserveGroup != null) result += """reserveGroup=${sanitize(reserveGroup)}"""
    if (enrollmentCapacity != null) result += """enrollmentCapacity=$enrollmentCapacity"""
    if (enrollmentTotal != null) result += """enrollmentTotal=$enrollmentTotal"""
    return result.joinToString(prefix = "Reserve{", separator = ", ", postfix = "}")
  }

  fun copy(
    reserveGroup: String? = this.reserveGroup,
    enrollmentCapacity: Int? = this.enrollmentCapacity,
    enrollmentTotal: Int? = this.enrollmentTotal,
    unknownFields: ByteString = this.unknownFields
  ): Reserve = Reserve(reserveGroup, enrollmentCapacity, enrollmentTotal, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<Reserve> = object : ProtoAdapter<Reserve>(
      FieldEncoding.LENGTH_DELIMITED, 
      Reserve::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.Reserve"
    ) {
      override fun encodedSize(value: Reserve): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.reserveGroup) +
        ProtoAdapter.INT32.encodedSizeWithTag(2, value.enrollmentCapacity) +
        ProtoAdapter.INT32.encodedSizeWithTag(3, value.enrollmentTotal) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: Reserve) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.reserveGroup)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.enrollmentCapacity)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.enrollmentTotal)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): Reserve {
        var reserveGroup: String? = null
        var enrollmentCapacity: Int? = null
        var enrollmentTotal: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> reserveGroup = ProtoAdapter.STRING.decode(reader)
            2 -> enrollmentCapacity = ProtoAdapter.INT32.decode(reader)
            3 -> enrollmentTotal = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Reserve(
          reserveGroup = reserveGroup,
          enrollmentCapacity = enrollmentCapacity,
          enrollmentTotal = enrollmentTotal,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: Reserve): Reserve = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
