// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class StudentProfile(
  @field:WireField(
    tag = 1,
    adapter = "com.watcourses.wat_courses.proto.Schedule#ADAPTER"
  )
  val schedule: Schedule? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val labels: List<String> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED
  )
  val degrees: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<StudentProfile, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StudentProfile) return false
    return unknownFields == other.unknownFields
        && schedule == other.schedule
        && labels == other.labels
        && degrees == other.degrees
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + schedule.hashCode()
      result = result * 37 + labels.hashCode()
      result = result * 37 + degrees.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (schedule != null) result += """schedule=$schedule"""
    if (labels.isNotEmpty()) result += """labels=${sanitize(labels)}"""
    if (degrees.isNotEmpty()) result += """degrees=${sanitize(degrees)}"""
    return result.joinToString(prefix = "StudentProfile{", separator = ", ", postfix = "}")
  }

  fun copy(
    schedule: Schedule? = this.schedule,
    labels: List<String> = this.labels,
    degrees: List<String> = this.degrees,
    unknownFields: ByteString = this.unknownFields
  ): StudentProfile = StudentProfile(schedule, labels, degrees, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<StudentProfile> = object : ProtoAdapter<StudentProfile>(
      FieldEncoding.LENGTH_DELIMITED, 
      StudentProfile::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.StudentProfile"
    ) {
      override fun encodedSize(value: StudentProfile): Int = 
        Schedule.ADAPTER.encodedSizeWithTag(1, value.schedule) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.labels) +
        ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.degrees) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: StudentProfile) {
        Schedule.ADAPTER.encodeWithTag(writer, 1, value.schedule)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.labels)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.degrees)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): StudentProfile {
        var schedule: Schedule? = null
        val labels = mutableListOf<String>()
        val degrees = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> schedule = Schedule.ADAPTER.decode(reader)
            2 -> labels.add(ProtoAdapter.STRING.decode(reader))
            3 -> degrees.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return StudentProfile(
          schedule = schedule,
          labels = labels,
          degrees = degrees,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: StudentProfile): StudentProfile = value.copy(
        schedule = value.schedule?.let(Schedule.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
