// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: uwflow.proto
package com.watcourses.wat_courses.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class UwFlowCourseRating(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val liked: Double? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val easy: Double? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  val useful: Double? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val filledCount: Int? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  val commentCount: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<UwFlowCourseRating, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UwFlowCourseRating) return false
    return unknownFields == other.unknownFields
        && liked == other.liked
        && easy == other.easy
        && useful == other.useful
        && filledCount == other.filledCount
        && commentCount == other.commentCount
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + liked.hashCode()
      result = result * 37 + easy.hashCode()
      result = result * 37 + useful.hashCode()
      result = result * 37 + filledCount.hashCode()
      result = result * 37 + commentCount.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (liked != null) result += """liked=$liked"""
    if (easy != null) result += """easy=$easy"""
    if (useful != null) result += """useful=$useful"""
    if (filledCount != null) result += """filledCount=$filledCount"""
    if (commentCount != null) result += """commentCount=$commentCount"""
    return result.joinToString(prefix = "UwFlowCourseRating{", separator = ", ", postfix = "}")
  }

  fun copy(
    liked: Double? = this.liked,
    easy: Double? = this.easy,
    useful: Double? = this.useful,
    filledCount: Int? = this.filledCount,
    commentCount: Int? = this.commentCount,
    unknownFields: ByteString = this.unknownFields
  ): UwFlowCourseRating = UwFlowCourseRating(liked, easy, useful, filledCount, commentCount,
      unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<UwFlowCourseRating> = object : ProtoAdapter<UwFlowCourseRating>(
      FieldEncoding.LENGTH_DELIMITED, 
      UwFlowCourseRating::class, 
      "type.googleapis.com/com.watcourses.wat_courses.proto.UwFlowCourseRating"
    ) {
      override fun encodedSize(value: UwFlowCourseRating): Int = 
        ProtoAdapter.DOUBLE.encodedSizeWithTag(1, value.liked) +
        ProtoAdapter.DOUBLE.encodedSizeWithTag(2, value.easy) +
        ProtoAdapter.DOUBLE.encodedSizeWithTag(3, value.useful) +
        ProtoAdapter.INT32.encodedSizeWithTag(4, value.filledCount) +
        ProtoAdapter.INT32.encodedSizeWithTag(5, value.commentCount) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: UwFlowCourseRating) {
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.liked)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.easy)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 3, value.useful)
        ProtoAdapter.INT32.encodeWithTag(writer, 4, value.filledCount)
        ProtoAdapter.INT32.encodeWithTag(writer, 5, value.commentCount)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): UwFlowCourseRating {
        var liked: Double? = null
        var easy: Double? = null
        var useful: Double? = null
        var filledCount: Int? = null
        var commentCount: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> liked = ProtoAdapter.DOUBLE.decode(reader)
            2 -> easy = ProtoAdapter.DOUBLE.decode(reader)
            3 -> useful = ProtoAdapter.DOUBLE.decode(reader)
            4 -> filledCount = ProtoAdapter.INT32.decode(reader)
            5 -> commentCount = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UwFlowCourseRating(
          liked = liked,
          easy = easy,
          useful = useful,
          filledCount = filledCount,
          commentCount = commentCount,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: UwFlowCourseRating): UwFlowCourseRating = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
