include = []
courses = ["ANTH *","AE 101","ARTS 490","BET 100","BET 300","BET 320","BET 340","BET 350","BET 400","BET 430",
"BET 450","EASIA 100R","CLAS *","ENVS 195","ENVS 205   ","FR 296","FR 297","GENE 22C","GENE 412","GEOG 101",
"GEOG 202","GEOG 203","GEOG 368","GERON 201","HLTH 320","HRM *","HUMSC 101","HUMSC 102","INTST 101","KIN 352",
"KIN 354","INTEG 120","INTEG 210","INTEG 220","INTEG 221","INTEG 251","LS 101","LS 202","MSCI 211","MSCI 263",
"MSCI 311","MSCI 411 ","MUSIC 140","MUSIC 253","MUSIC 256","MUSIC 334","MUSIC 355","MUSIC 363","PACS *","PLAN 100",
"REC 230","REC 425","SMF *","STV *","SI 121R","SI 132R","SI 221R","SI 230R","SI 231R","SI 315R","THPERF 100",
"THPERF 200","ECON *", "ENGL *", "GSJ *","PHIL *","PSCI *", "PSYCH *", "SOC *", "SDS *", "SOCWK *", "RS *", "HIST *"
]
except = [
 "ECON 211","ECON 221","ECON 311","ECON 371","ECON 412","ECON 421","ECON 422","ECON 471 ENGL 109","ENGL 119",
 "ENGL 129R","ENGL 140R","ENGL 210E","ENGL 210F", "GSJ 371","PHIL 145","PHIL 200J","PHIL 216","PHIL 240","PHIL 256",
 "PHIL 257","PHIL 441","PSCI 314","PSCI 315", "PSYCH 256","PSYCH 261","PSYCH 291","PSYCH 292","PSYCH 307","PSYCH 312",
 "PSYCH 317","PSYCH 391","PSYCH 4*", "SOC 221","SOC 280","SOC 322","SOC 498","SOC 499A","SOC 499B","SDS 150R",
 "SDS 250R","SDS 251R","SDS 350R","SDS 398R", "SDS 399R","SOCWK 390A","SOCWK 390B","SOCWK 398R","SOCWK 399R","RS 131",
 "RS 132","HIST 4*"
]
notes = [
 "GSJ 371 may be acceptable at the discretion of the associate chair when a course outline is shown",
 "PSYCH 400-level courses need approval of the Department of Psychology"
]