include = []
courses = ["PD 10",
          "PD 11",
          "PD 12",
          "PD 13",
          "PD 19",
          "PD 22",
          "PD 3",
          "PD 4",
          "PD 5",
          "PD 6",
          "PD 7",
          "PD 8",
          "PD 9",
          "PD 20",
          "PD 21"]