include = []
courses = ["BIOL 110","BIOL 120","BIOL 130","BIOL 130L","BIOL 150","BIOL 165","BIOL 239","BIOL 240","BIOL 273",
           "CHE 161","CHEM 262","CHEM 262L","EARTH 121","EARTH 122","PHYS 124","PHYS 175","PHYS 234","PHYS 263",
           "PHYS 275","PHYS 334","PHYS 375","SCI 238","SCI 250"]