include = []
courses = ["BET 420",
           "BME 381",
           "ECE 390",
           "ENVS 105",
           "ENVS 205",
           "ERS 215",
           "ERS 315",
           "GENE 22A",
           "GEOG 203",
           "GEOG 207",
           "GEOG 368",
           "GSJ 205",
           "MSCI 422",
           "MSCI 442",
           "NE 109",
           "PHIL 226",
           "SOC 232",
           "STV 100",
           "STV 202",
           "STV 205",
           "STV 210",
           "STV 302",
           "STV 304",
           "STV 305",
           "STV 306",
           "SYDE 261"
]
