// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: courses.proto
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class CourseInfo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val name: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val code: String? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val description: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val faculty: String? = null,
  @field:WireField(
    tag = 5,
    adapter = "Term#ADAPTER"
  )
  val offeringTerm: Term? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<CourseInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CourseInfo) return false
    return unknownFields == other.unknownFields
        && name == other.name
        && code == other.code
        && description == other.description
        && faculty == other.faculty
        && offeringTerm == other.offeringTerm
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + code.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + faculty.hashCode()
      result = result * 37 + offeringTerm.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (name != null) result += """name=${sanitize(name)}"""
    if (code != null) result += """code=${sanitize(code)}"""
    if (description != null) result += """description=${sanitize(description)}"""
    if (faculty != null) result += """faculty=${sanitize(faculty)}"""
    if (offeringTerm != null) result += """offeringTerm=$offeringTerm"""
    return result.joinToString(prefix = "CourseInfo{", separator = ", ", postfix = "}")
  }

  fun copy(
    name: String? = this.name,
    code: String? = this.code,
    description: String? = this.description,
    faculty: String? = this.faculty,
    offeringTerm: Term? = this.offeringTerm,
    unknownFields: ByteString = this.unknownFields
  ): CourseInfo = CourseInfo(name, code, description, faculty, offeringTerm, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<CourseInfo> = object : ProtoAdapter<CourseInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      CourseInfo::class, 
      "type.googleapis.com/CourseInfo"
    ) {
      override fun encodedSize(value: CourseInfo): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.code) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.description) +
        ProtoAdapter.STRING.encodedSizeWithTag(4, value.faculty) +
        Term.ADAPTER.encodedSizeWithTag(5, value.offeringTerm) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: CourseInfo) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.code)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.description)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.faculty)
        Term.ADAPTER.encodeWithTag(writer, 5, value.offeringTerm)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): CourseInfo {
        var name: String? = null
        var code: String? = null
        var description: String? = null
        var faculty: String? = null
        var offeringTerm: Term? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> code = ProtoAdapter.STRING.decode(reader)
            3 -> description = ProtoAdapter.STRING.decode(reader)
            4 -> faculty = ProtoAdapter.STRING.decode(reader)
            5 -> try {
              offeringTerm = Term.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return CourseInfo(
          name = name,
          code = code,
          description = description,
          faculty = faculty,
          offeringTerm = offeringTerm,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: CourseInfo): CourseInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
